// B1 German Vocabulary Data
// Source: High Frequency German Vocabulary for B1 Learners (Olesen Tuition)
// Structure: each word has german (with article if noun), article, english, genderTip, pos

// Gender tip reference (used for nouns):
// -ung → always die
// -heit, -keit, -schaft, -tion, -tät, -ung, -enz, -ie → always die
// -chen, -lein → always das
// -er (agent nouns, masc person) → usually der
// -nis → usually das (occasionally die)
// -ment → usually das
// Compound nouns take the gender of the LAST component

const LESSONS = [
  {
    lesson: 1,
    title: "Character & Personality Traits",
    words: [
      { german: "ehrlich", article: null, english: "honest", genderTip: null, pos: "adj" },
      { german: "unehrlich", article: null, english: "dishonest", genderTip: null, pos: "adj" },
      { german: "zuverlässig", article: null, english: "reliable, dependable", genderTip: null, pos: "adj" },
      { german: "unzuverlässig", article: null, english: "unreliable", genderTip: null, pos: "adj" },
      { german: "selbstbewusst", article: null, english: "self-confident", genderTip: null, pos: "adj" },
      { german: "offen", article: null, english: "open, frank, open-minded", genderTip: null, pos: "adj" },
      { german: "zurückhaltend", article: null, english: "reserved, cautious", genderTip: null, pos: "adj" },
      { german: "kreativ", article: null, english: "creative", genderTip: null, pos: "adj" },
      { german: "intelligent", article: null, english: "intelligent, smart", genderTip: null, pos: "adj" },
      { german: "dumm", article: null, english: "dumb, foolish", genderTip: null, pos: "adj" },
      { german: "fleißig", article: null, english: "hard-working, diligent", genderTip: null, pos: "adj" },
      { german: "faul", article: null, english: "lazy", genderTip: null, pos: "adj" },
      { german: "ehrgeizig", article: null, english: "ambitious", genderTip: null, pos: "adj" },
      { german: "ambitioniert", article: null, english: "ambitious (goal-setting context)", genderTip: null, pos: "adj" },
      { german: "großzügig", article: null, english: "generous", genderTip: null, pos: "adj" },
      { german: "egoistisch", article: null, english: "selfish, egotistical", genderTip: null, pos: "adj" },
      { german: "gemein", article: null, english: "mean, nasty", genderTip: null, pos: "adj" },
      { german: "witzig", article: null, english: "funny, witty", genderTip: null, pos: "adj" },
      { german: "höflich", article: null, english: "polite", genderTip: null, pos: "adj" },
      { german: "unhöflich", article: null, english: "impolite, rude", genderTip: null, pos: "adj" },
      { german: "frech", article: null, english: "cheeky, bold (playfully rude)", genderTip: null, pos: "adj" },
      { german: "neugierig", article: null, english: "curious, nosy", genderTip: null, pos: "adj" },
      { german: "bescheiden", article: null, english: "modest, humble", genderTip: null, pos: "adj" },
    ]
  },
  {
    lesson: 2,
    title: "Friendships & Relationships",
    words: [
      { german: "der Freund", article: "der", english: "friend (male); boyfriend", genderTip: "-nd agent noun → der", pos: "noun" },
      { german: "die Freundin", article: "die", english: "friend (female); girlfriend", genderTip: "-in suffix (feminine person) → always die", pos: "noun" },
      { german: "der Bekannte", article: "der", english: "acquaintance (male)", genderTip: "adjectival noun from bekannt → der/die depending on gender", pos: "noun" },
      { german: "die Freundschaft", article: "die", english: "friendship", genderTip: "-schaft words are always feminine → die", pos: "noun" },
      { german: "die Beziehung", article: "die", english: "relationship", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Liebe", article: "die", english: "love", genderTip: "no rule — memorise: die Liebe", pos: "noun" },
      { german: "verliebt", article: null, english: "in love", genderTip: null, pos: "adj" },
      { german: "sich verlieben", article: null, english: "to fall in love", genderTip: null, pos: "verb" },
      { german: "zusammen sein", article: null, english: "to be together (as a couple)", genderTip: null, pos: "verb" },
      { german: "das Paar", article: "das", english: "couple, pair", genderTip: "no rule — memorise: das Paar", pos: "noun" },
      { german: "die Ehe", article: "die", english: "marriage", genderTip: "no rule — memorise: die Ehe", pos: "noun" },
      { german: "verheiratet", article: null, english: "married", genderTip: null, pos: "adj" },
      { german: "ledig", article: null, english: "single (unmarried)", genderTip: null, pos: "adj" },
      { german: "geschieden", article: null, english: "divorced", genderTip: null, pos: "adj" },
      { german: "sich verstehen", article: null, english: "to get along with someone", genderTip: null, pos: "verb" },
      { german: "sich streiten", article: null, english: "to argue, quarrel", genderTip: null, pos: "verb" },
      { german: "der Streit", article: "der", english: "argument, quarrel", genderTip: "no rule — memorise: der Streit", pos: "noun" },
      { german: "die Scheidung", article: "die", english: "divorce", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "sich scheiden lassen", article: null, english: "to get divorced", genderTip: null, pos: "verb" },
      { german: "der Ehemann", article: "der", english: "husband", genderTip: "compound: last component Mann → der", pos: "noun" },
      { german: "die Ehefrau", article: "die", english: "wife", genderTip: "compound: last component Frau → die", pos: "noun" },
      { german: "das Mitglied", article: "das", english: "member (of a family or group)", genderTip: "-glied compound → das", pos: "noun" },
      { german: "die Geschwister", article: "die", english: "siblings (brothers and sisters)", genderTip: "plural only noun → die (pl.)", pos: "noun" },
      { german: "die Eltern", article: "die", english: "parents", genderTip: "plural only noun → die (pl.)", pos: "noun" },
      { german: "die Verwandten", article: "die", english: "relatives, extended family", genderTip: "plural of adjectival noun → die (pl.)", pos: "noun" },
      { german: "der Nachbar", article: "der", english: "neighbour (male)", genderTip: "person noun → der", pos: "noun" },
      { german: "der Kollege", article: "der", english: "colleague (male)", genderTip: "person noun → der", pos: "noun" },
      { german: "vertrauen", article: null, english: "to trust", genderTip: null, pos: "verb" },
      { german: "sich kümmern um", article: null, english: "to take care of someone/something", genderTip: null, pos: "verb" },
      { german: "unterstützen", article: null, english: "to support (emotionally or financially)", genderTip: null, pos: "verb" },
    ]
  },
  {
    lesson: 3,
    title: "City & Country Life",
    words: [
      { german: "die Großstadt", article: "die", english: "big city, metropolis", genderTip: "compound: last component Stadt → die", pos: "noun" },
      { german: "das Dorf", article: "das", english: "village", genderTip: "no rule — memorise: das Dorf", pos: "noun" },
      { german: "das Stadtzentrum", article: "das", english: "city centre, downtown", genderTip: "compound: last component Zentrum → das", pos: "noun" },
      { german: "der Stadtrand", article: "der", english: "outskirts of a city, suburbia", genderTip: "compound: last component Rand → der", pos: "noun" },
      { german: "das Land", article: "das", english: "countryside, rural area", genderTip: "no rule — memorise: das Land", pos: "noun" },
      { german: "ländlich", article: null, english: "rural", genderTip: null, pos: "adj" },
      { german: "städtisch", article: null, english: "urban, city-", genderTip: null, pos: "adj" },
      { german: "das Stadtleben", article: "das", english: "city life", genderTip: "compound: last component Leben → das", pos: "noun" },
      { german: "das Landleben", article: "das", english: "country life", genderTip: "compound: last component Leben → das", pos: "noun" },
      { german: "die Umgebung", article: "die", english: "surroundings, vicinity", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Infrastruktur", article: "die", english: "infrastructure", genderTip: "-ur suffix → usually die", pos: "noun" },
      { german: "die öffentlichen Verkehrsmittel", article: "die", english: "public transportation", genderTip: "plural: Mittel (das) → die (pl.)", pos: "noun" },
      { german: "der Verkehr", article: "der", english: "traffic", genderTip: "no rule — memorise: der Verkehr", pos: "noun" },
      { german: "der Stau", article: "der", english: "traffic jam", genderTip: "no rule — memorise: der Stau", pos: "noun" },
      { german: "die U-Bahn", article: "die", english: "subway, underground train", genderTip: "compound: last component Bahn → die", pos: "noun" },
      { german: "der Bahnhof", article: "der", english: "train station", genderTip: "compound: last component Hof → der", pos: "noun" },
      { german: "die Luftverschmutzung", article: "die", english: "air pollution", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Lärm", article: "der", english: "noise, noise pollution", genderTip: "no rule — memorise: der Lärm", pos: "noun" },
      { german: "laut", article: null, english: "loud, noisy", genderTip: null, pos: "adj" },
      { german: "ruhig", article: null, english: "quiet, calm", genderTip: null, pos: "adj" },
      { german: "die Ruhe", article: "die", english: "peace, quiet", genderTip: "no rule — memorise: die Ruhe", pos: "noun" },
      { german: "hektisch", article: null, english: "hectic, frenzied", genderTip: null, pos: "adj" },
      { german: "entspannt", article: null, english: "relaxed, laid-back", genderTip: null, pos: "adj" },
      { german: "anonym", article: null, english: "anonymous, impersonal", genderTip: null, pos: "adj" },
      { german: "persönlich", article: null, english: "personal", genderTip: null, pos: "adj" },
      { german: "das Angebot", article: "das", english: "offer; range of things available", genderTip: "-bot compound → das", pos: "noun" },
      { german: "vielfältig", article: null, english: "diverse, varied", genderTip: null, pos: "adj" },
      { german: "die Einkaufsmöglichkeit", article: "die", english: "shopping opportunity/option", genderTip: "-keit words are always feminine → die", pos: "noun" },
      { german: "der Bauernhof", article: "der", english: "farm, farmhouse", genderTip: "compound: last component Hof → der", pos: "noun" },
      { german: "praktisch", article: null, english: "convenient, practical", genderTip: null, pos: "adj" },
      { german: "ungünstig", article: null, english: "inconvenient, unfavourable", genderTip: null, pos: "adj" },
      { german: "die Lebensqualität", article: "die", english: "quality of life", genderTip: "-tät words are always feminine → die", pos: "noun" },
      { german: "die Sicherheit", article: "die", english: "safety, security", genderTip: "-heit words are always feminine → die", pos: "noun" },
      { german: "sicher", article: null, english: "safe; sure, certain", genderTip: null, pos: "adj" },
      { german: "die Arbeitsmöglichkeit", article: "die", english: "job opportunity", genderTip: "-keit words are always feminine → die", pos: "noun" },
      { german: "die Freizeitmöglichkeit", article: "die", english: "leisure opportunity", genderTip: "-keit words are always feminine → die", pos: "noun" },
      { german: "das Kulturangebot", article: "das", english: "cultural offerings (museums, theatres)", genderTip: "compound: last component Angebot → das", pos: "noun" },
      { german: "die Nachbarschaft", article: "die", english: "neighbourhood", genderTip: "-schaft words are always feminine → die", pos: "noun" },
    ]
  },
  {
    lesson: 4,
    title: "Nature & Weather",
    words: [
      { german: "die Landschaft", article: "die", english: "landscape, scenery", genderTip: "-schaft words are always feminine → die", pos: "noun" },
      { german: "der Berg", article: "der", english: "mountain", genderTip: "no rule — memorise: der Berg", pos: "noun" },
      { german: "das Tal", article: "das", english: "valley", genderTip: "no rule — memorise: das Tal", pos: "noun" },
      { german: "der Hügel", article: "der", english: "hill", genderTip: "no rule — memorise: der Hügel", pos: "noun" },
      { german: "der Wald", article: "der", english: "forest, woods", genderTip: "no rule — memorise: der Wald", pos: "noun" },
      { german: "der Baum", article: "der", english: "tree", genderTip: "no rule — memorise: der Baum", pos: "noun" },
      { german: "der Hund", article: "der", english: "dog", genderTip: "no rule — memorise: der Hund", pos: "noun" },
      { german: "der See", article: "der", english: "lake (note: die See = the sea)", genderTip: "der See = lake; die See = sea — must memorise both!", pos: "noun" },
      { german: "der Fluss", article: "der", english: "river", genderTip: "no rule — memorise: der Fluss", pos: "noun" },
      { german: "der Bach", article: "der", english: "stream, creek", genderTip: "no rule — memorise: der Bach", pos: "noun" },
      { german: "der Strand", article: "der", english: "beach, shore", genderTip: "no rule — memorise: der Strand", pos: "noun" },
      { german: "die Insel", article: "die", english: "island", genderTip: "no rule — memorise: die Insel", pos: "noun" },
      { german: "das Wetter", article: "das", english: "weather", genderTip: "no rule — memorise: das Wetter", pos: "noun" },
      { german: "das Klima", article: "das", english: "climate", genderTip: "no rule — memorise: das Klima", pos: "noun" },
      { german: "warm", article: null, english: "warm", genderTip: null, pos: "adj" },
      { german: "heiß", article: null, english: "hot", genderTip: null, pos: "adj" },
      { german: "kalt", article: null, english: "cold", genderTip: null, pos: "adj" },
      { german: "kühl", article: null, english: "cool, chilly", genderTip: null, pos: "adj" },
      { german: "trocken", article: null, english: "dry", genderTip: null, pos: "adj" },
      { german: "nass", article: null, english: "wet", genderTip: null, pos: "adj" },
      { german: "feucht", article: null, english: "humid, damp", genderTip: null, pos: "adj" },
      { german: "die Sonne", article: "die", english: "sun", genderTip: "no rule — memorise: die Sonne", pos: "noun" },
      { german: "sonnig", article: null, english: "sunny", genderTip: null, pos: "adj" },
      { german: "die Wolke", article: "die", english: "cloud", genderTip: "no rule — memorise: die Wolke", pos: "noun" },
      { german: "wolkig", article: null, english: "cloudy", genderTip: null, pos: "adj" },
      { german: "der Regen", article: "der", english: "rain", genderTip: "no rule — memorise: der Regen", pos: "noun" },
      { german: "regnerisch", article: null, english: "rainy", genderTip: null, pos: "adj" },
      { german: "regnen", article: null, english: "to rain", genderTip: null, pos: "verb" },
      { german: "der Schnee", article: "der", english: "snow", genderTip: "no rule — memorise: der Schnee", pos: "noun" },
      { german: "schneien", article: null, english: "to snow", genderTip: null, pos: "verb" },
      { german: "der Wind", article: "der", english: "wind", genderTip: "no rule — memorise: der Wind", pos: "noun" },
      { german: "windig", article: null, english: "windy", genderTip: null, pos: "adj" },
      { german: "der Sturm", article: "der", english: "storm, high winds", genderTip: "no rule — memorise: der Sturm", pos: "noun" },
      { german: "stürmisch", article: null, english: "stormy", genderTip: null, pos: "adj" },
      { german: "das Gewitter", article: "das", english: "thunderstorm (with lightning)", genderTip: "no rule — memorise: das Gewitter", pos: "noun" },
      { german: "der Donner", article: "der", english: "thunder", genderTip: "no rule — memorise: der Donner", pos: "noun" },
      { german: "der Blitz", article: "der", english: "lightning; flash", genderTip: "no rule — memorise: der Blitz", pos: "noun" },
      { german: "der Nebel", article: "der", english: "fog", genderTip: "no rule — memorise: der Nebel", pos: "noun" },
      { german: "neblig", article: null, english: "foggy", genderTip: null, pos: "adj" },
      { german: "das Unwetter", article: "das", english: "severe weather, bad storm", genderTip: "compound: last component Wetter → das", pos: "noun" },
      { german: "der Wetterbericht", article: "der", english: "weather report/forecast", genderTip: "compound: last component Bericht → der", pos: "noun" },
      { german: "die Jahreszeit", article: "die", english: "season (spring, summer, etc.)", genderTip: "compound: last component Zeit → die", pos: "noun" },
      { german: "der Frühling", article: "der", english: "spring", genderTip: "no rule — memorise: der Frühling", pos: "noun" },
      { german: "der Sommer", article: "der", english: "summer", genderTip: "seasons are always der", pos: "noun" },
      { german: "der Herbst", article: "der", english: "autumn, fall", genderTip: "seasons are always der", pos: "noun" },
      { german: "der Winter", article: "der", english: "winter", genderTip: "seasons are always der", pos: "noun" },
    ]
  },
  {
    lesson: 5,
    title: "Environmental Issues & Climate Change",
    words: [
      { german: "die Umwelt", article: "die", english: "environment", genderTip: "compound: last component Welt → die", pos: "noun" },
      { german: "der Umweltschutz", article: "der", english: "environmental protection", genderTip: "compound: last component Schutz → der", pos: "noun" },
      { german: "der Klimawandel", article: "der", english: "climate change", genderTip: "compound: last component Wandel → der", pos: "noun" },
      { german: "die Erderwärmung", article: "die", english: "global warming", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Treibhauseffekt", article: "der", english: "greenhouse effect", genderTip: "compound: last component Effekt → der", pos: "noun" },
      { german: "die Energie", article: "die", english: "energy", genderTip: "-ie words are often feminine → die", pos: "noun" },
      { german: "erneuerbare Energie", article: null, english: "renewable energy", genderTip: null, pos: "phrase" },
      { german: "die Umweltverschmutzung", article: "die", english: "environmental pollution", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "verschmutzen", article: null, english: "to pollute", genderTip: null, pos: "verb" },
      { german: "das Abgas", article: "das", english: "exhaust emission", genderTip: "compound: last component Gas → das", pos: "noun" },
      { german: "der Müll", article: "der", english: "garbage, waste", genderTip: "no rule — memorise: der Müll", pos: "noun" },
      { german: "recyceln", article: null, english: "to recycle", genderTip: null, pos: "verb" },
      { german: "das Recycling", article: "das", english: "recycling", genderTip: "-ing (English loanword) → das", pos: "noun" },
      { german: "die Verpackung", article: "die", english: "packaging", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "plastikfrei", article: null, english: "plastic-free", genderTip: null, pos: "adj" },
      { german: "die Plastiktüte", article: "die", english: "plastic bag", genderTip: "compound: last component Tüte → die", pos: "noun" },
      { german: "die Mehrwegflasche", article: "die", english: "reusable bottle", genderTip: "compound: last component Flasche → die", pos: "noun" },
      { german: "das Pfand", article: "das", english: "deposit (on returnable bottles)", genderTip: "no rule — memorise: das Pfand", pos: "noun" },
      { german: "die Solarenergie", article: "die", english: "solar energy", genderTip: "-ie words are often feminine → die", pos: "noun" },
      { german: "die Windkraft", article: "die", english: "wind power", genderTip: "compound: last component Kraft → die", pos: "noun" },
      { german: "die Nachhaltigkeit", article: "die", english: "sustainability", genderTip: "-keit words are always feminine → die", pos: "noun" },
      { german: "nachhaltig", article: null, english: "sustainable, sustainably", genderTip: null, pos: "adj" },
      { german: "umweltfreundlich", article: null, english: "environmentally friendly, eco-friendly", genderTip: null, pos: "adj" },
      { german: "schützen", article: null, english: "to protect", genderTip: null, pos: "verb" },
      { german: "erhalten", article: null, english: "to preserve, conserve", genderTip: null, pos: "verb" },
      { german: "retten", article: null, english: "to save, rescue", genderTip: null, pos: "verb" },
      { german: "bedrohen", article: null, english: "to threaten", genderTip: null, pos: "verb" },
      { german: "gefährdet", article: null, english: "endangered, at risk", genderTip: null, pos: "adj" },
      { german: "die Gefahr", article: "die", english: "danger", genderTip: "no rule — memorise: die Gefahr", pos: "noun" },
      { german: "das Aussterben", article: "das", english: "extinction", genderTip: "nominalised infinitive → always das", pos: "noun" },
      { german: "die Naturkatastrophe", article: "die", english: "natural disaster", genderTip: "compound: last component Katastrophe → die", pos: "noun" },
      { german: "die Überschwemmung", article: "die", english: "flood", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "das Hochwasser", article: "das", english: "flooding, high water", genderTip: "compound: last component Wasser → das", pos: "noun" },
      { german: "die Dürre", article: "die", english: "drought", genderTip: "no rule — memorise: die Dürre", pos: "noun" },
    ]
  },
  {
    lesson: 6,
    title: "Education & Training",
    words: [
      { german: "die Grundschule", article: "die", english: "primary school, elementary school", genderTip: "compound: last component Schule → die", pos: "noun" },
      { german: "die weiterführende Schule", article: "die", english: "secondary school", genderTip: "compound: last component Schule → die", pos: "noun" },
      { german: "das Gymnasium", article: "das", english: "high school / college-prep school in Germany", genderTip: "-ium words → usually das", pos: "noun" },
      { german: "die Universität", article: "die", english: "university", genderTip: "-tät words are always feminine → die", pos: "noun" },
      { german: "die Hochschule", article: "die", english: "college, higher education institution", genderTip: "compound: last component Schule → die", pos: "noun" },
      { german: "der Studiengang", article: "der", english: "degree programme, course of study", genderTip: "compound: last component Gang → der", pos: "noun" },
      { german: "das Semester", article: "das", english: "semester", genderTip: "no rule — memorise: das Semester", pos: "noun" },
      { german: "die Vorlesung", article: "die", english: "lecture (university class)", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Professor", article: "der", english: "professor (male)", genderTip: "person noun (male) → der", pos: "noun" },
      { german: "die Ausbildung", article: "die", english: "vocational training, apprenticeship", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Auszubildende", article: "der", english: "apprentice, trainee", genderTip: "adjectival noun → der (male)", pos: "noun" },
      { german: "die Berufsschule", article: "die", english: "vocational school, trade school", genderTip: "compound: last component Schule → die", pos: "noun" },
      { german: "die Weiterbildung", article: "die", english: "further education, advanced training", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Kurs", article: "der", english: "course, class", genderTip: "no rule — memorise: der Kurs", pos: "noun" },
      { german: "die Volkshochschule", article: "die", english: "adult education centre (VHS)", genderTip: "compound: last component Schule → die", pos: "noun" },
      { german: "das Praktikum", article: "das", english: "internship", genderTip: "-um words → usually das", pos: "noun" },
      { german: "die Theorie", article: "die", english: "theory", genderTip: "-ie words are often feminine → die", pos: "noun" },
      { german: "die Praxis", article: "die", english: "practice (as opposed to theory)", genderTip: "no rule — memorise: die Praxis", pos: "noun" },
      { german: "die Erfahrung", article: "die", english: "experience (knowledge gained)", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Kenntnisse", article: "die", english: "knowledge, skills in a particular area", genderTip: "-nisse → das Kenntnis (sg.) but used in plural die Kenntnisse", pos: "noun" },
      { german: "das Diplom", article: "das", english: "diploma, university degree", genderTip: "no rule — memorise: das Diplom", pos: "noun" },
      { german: "das Zeugnis", article: "das", english: "report card, certificate, transcript", genderTip: "-nis → usually das", pos: "noun" },
      { german: "der Abschluss", article: "der", english: "completion, degree (e.g. school leaving certificate)", genderTip: "compound: last component Schluss → der", pos: "noun" },
      { german: "das Abitur", article: "das", english: "high school leaving exam (German university entry)", genderTip: "no rule — memorise: das Abitur", pos: "noun" },
      { german: "die Prüfung", article: "die", english: "exam, test", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "das Examen", article: "das", english: "final exam, state exam", genderTip: "-men words → usually das", pos: "noun" },
      { german: "bestehen", article: null, english: "to pass (an exam)", genderTip: null, pos: "verb" },
      { german: "durchfallen", article: null, english: "to fail (an exam)", genderTip: null, pos: "verb" },
      { german: "sich anmelden", article: null, english: "to register, enrol", genderTip: null, pos: "verb" },
      { german: "die Anmeldung", article: "die", english: "registration, enrollment", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "das Stipendium", article: "das", english: "scholarship, stipend", genderTip: "-ium words → usually das", pos: "noun" },
      { german: "die Karriere", article: "die", english: "career, professional path", genderTip: "no rule — memorise: die Karriere", pos: "noun" },
      { german: "das Fernstudium", article: "das", english: "distance learning", genderTip: "-ium words → usually das", pos: "noun" },
    ]
  },
  {
    lesson: 7,
    title: "Hopes, Dreams & Ambitions",
    words: [
      { german: "der Traum", article: "der", english: "dream, aspiration", genderTip: "no rule — memorise: der Traum", pos: "noun" },
      { german: "träumen von", article: null, english: "to dream of/about something", genderTip: null, pos: "verb" },
      { german: "der Traumjob", article: "der", english: "dream job, ideal job", genderTip: "compound: last component Job → der", pos: "noun" },
      { german: "die Hoffnung", article: "die", english: "hope", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "hoffen", article: null, english: "to hope", genderTip: null, pos: "verb" },
      { german: "sich wünschen", article: null, english: "to wish for something", genderTip: null, pos: "verb" },
      { german: "der Wunsch", article: "der", english: "wish, desire", genderTip: "no rule — memorise: der Wunsch", pos: "noun" },
      { german: "ambitioniert", article: null, english: "ambitious", genderTip: null, pos: "adj" },
      { german: "die Ambition", article: "die", english: "ambition", genderTip: "-tion words are always feminine → die", pos: "noun" },
      { german: "das Ziel", article: "das", english: "goal, target", genderTip: "no rule — memorise: das Ziel", pos: "noun" },
      { german: "sich ein Ziel setzen", article: null, english: "to set oneself a goal", genderTip: null, pos: "verb" },
      { german: "erreichen", article: null, english: "to achieve, reach a goal", genderTip: null, pos: "verb" },
      { german: "erfolgreich", article: null, english: "successful", genderTip: null, pos: "adj" },
      { german: "der Erfolg", article: "der", english: "success", genderTip: "no rule — memorise: der Erfolg", pos: "noun" },
      { german: "die Karriereleiter", article: "die", english: "career ladder", genderTip: "compound: last component Leiter → die", pos: "noun" },
      { german: "aufsteigen", article: null, english: "to rise, get promoted", genderTip: null, pos: "verb" },
      { german: "die Zukunft", article: "die", english: "future", genderTip: "compound: last component Kunft → die (memorise)", pos: "noun" },
      { german: "planen", article: null, english: "to plan", genderTip: null, pos: "verb" },
      { german: "die Planung", article: "die", english: "planning", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "vorhaben", article: null, english: "to intend, to have planned", genderTip: null, pos: "verb" },
      { german: "die Vision", article: "die", english: "vision, visionary goal", genderTip: "-ion words are always feminine → die", pos: "noun" },
      { german: "die Wirklichkeit", article: "die", english: "reality", genderTip: "-keit words are always feminine → die", pos: "noun" },
      { german: "verwirklichen", article: null, english: "to realise, accomplish something", genderTip: null, pos: "verb" },
      { german: "sich bemühen", article: null, english: "to strive, make an effort", genderTip: null, pos: "verb" },
      { german: "die Anstrengung", article: "die", english: "effort", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "sich anstrengen", article: null, english: "to exert oneself, make a big effort", genderTip: null, pos: "verb" },
      { german: "aufgeben", article: null, english: "to give up", genderTip: null, pos: "verb" },
      { german: "durchhalten", article: null, english: "to persevere, hang on", genderTip: null, pos: "verb" },
      { german: "optimistisch", article: null, english: "optimistic", genderTip: null, pos: "adj" },
      { german: "pessimistisch", article: null, english: "pessimistic", genderTip: null, pos: "adj" },
      { german: "zuversichtlich", article: null, english: "confident, optimistic (certain of good outcome)", genderTip: null, pos: "adj" },
      { german: "die Inspiration", article: "die", english: "inspiration", genderTip: "-tion words are always feminine → die", pos: "noun" },
      { german: "die Motivation", article: "die", english: "motivation", genderTip: "-tion words are always feminine → die", pos: "noun" },
    ]
  },
  {
    lesson: 8,
    title: "Health, Fitness & Lifestyle",
    words: [
      { german: "gesund", article: null, english: "healthy", genderTip: null, pos: "adj" },
      { german: "ungesund", article: null, english: "unhealthy", genderTip: null, pos: "adj" },
      { german: "die Gesundheit", article: "die", english: "health", genderTip: "-heit words are always feminine → die", pos: "noun" },
      { german: "fit", article: null, english: "fit, in shape (physically)", genderTip: null, pos: "adj" },
      { german: "in Form sein", article: null, english: "to be in shape", genderTip: null, pos: "phrase" },
      { german: "die Fitness", article: "die", english: "fitness, physical fitness", genderTip: "no rule — memorise: die Fitness", pos: "noun" },
      { german: "Sport treiben", article: null, english: "to do sports, exercise", genderTip: null, pos: "phrase" },
      { german: "sich bewegen", article: null, english: "to exercise, be active", genderTip: null, pos: "verb" },
      { german: "die Bewegung", article: "die", english: "movement, exercise, physical activity", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "das Training", article: "das", english: "training, workout", genderTip: "-ing (English loanword) → das", pos: "noun" },
      { german: "trainieren", article: null, english: "to train, work out", genderTip: null, pos: "verb" },
      { german: "joggen", article: null, english: "to jog", genderTip: null, pos: "verb" },
      { german: "schwitzen", article: null, english: "to sweat", genderTip: null, pos: "verb" },
      { german: "die Ernährung", article: "die", english: "nutrition, diet (way of eating)", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "sich ernähren", article: null, english: "to feed oneself, to eat in a certain way", genderTip: null, pos: "verb" },
      { german: "die Diät", article: "die", english: "diet (for weight loss or medical reasons)", genderTip: "no rule — memorise: die Diät", pos: "noun" },
      { german: "das Gewicht", article: "das", english: "weight", genderTip: "no rule — memorise: das Gewicht", pos: "noun" },
      { german: "abnehmen", article: null, english: "to lose weight", genderTip: null, pos: "verb" },
      { german: "zunehmen", article: null, english: "to gain weight", genderTip: null, pos: "verb" },
      { german: "wiegen", article: null, english: "to weigh", genderTip: null, pos: "verb" },
      { german: "die Kalorie", article: "die", english: "calorie", genderTip: "no rule — memorise: die Kalorie", pos: "noun" },
      { german: "kalorienarm", article: null, english: "low in calories", genderTip: null, pos: "adj" },
      { german: "kalorienreich", article: null, english: "high in calories", genderTip: null, pos: "adj" },
      { german: "fettig", article: null, english: "fatty, greasy", genderTip: null, pos: "adj" },
      { german: "vegetarisch", article: null, english: "vegetarian", genderTip: null, pos: "adj" },
      { german: "vegan", article: null, english: "vegan", genderTip: null, pos: "adj" },
      { german: "die Krankheit", article: "die", english: "illness, disease", genderTip: "-heit words are always feminine → die", pos: "noun" },
      { german: "krank", article: null, english: "sick, ill", genderTip: null, pos: "adj" },
      { german: "sich erholen", article: null, english: "to recuperate, recover", genderTip: null, pos: "verb" },
      { german: "die Erholung", article: "die", english: "recovery, rest", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Schlaf", article: "der", english: "sleep", genderTip: "no rule — memorise: der Schlaf", pos: "noun" },
      { german: "ausschlafen", article: null, english: "to sleep in, sleep enough", genderTip: null, pos: "verb" },
      { german: "müde", article: null, english: "tired", genderTip: null, pos: "adj" },
      { german: "energisch", article: null, english: "energetic, full of energy", genderTip: null, pos: "adj" },
      { german: "der Stress", article: "der", english: "stress", genderTip: "no rule — memorise: der Stress", pos: "noun" },
      { german: "gestresst", article: null, english: "stressed", genderTip: null, pos: "adj" },
      { german: "stressig", article: null, english: "stressful", genderTip: null, pos: "adj" },
      { german: "sich entspannen", article: null, english: "to relax, unwind", genderTip: null, pos: "verb" },
      { german: "die Entspannung", article: "die", english: "relaxation", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "sich ausruhen", article: null, english: "to rest, chill out", genderTip: null, pos: "verb" },
      { german: "das Wohlbefinden", article: "das", english: "well-being", genderTip: "nominalised infinitive → always das", pos: "noun" },
      { german: "sich wohl fühlen", article: null, english: "to feel well, feel comfortable", genderTip: null, pos: "verb" },
      { german: "die Gewohnheit", article: "die", english: "habit", genderTip: "-heit words are always feminine → die", pos: "noun" },
      { german: "die Herausforderung", article: "die", english: "challenge", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "sich vornehmen", article: null, english: "to resolve to do something, set a goal", genderTip: null, pos: "verb" },
    ]
  },
  {
    lesson: 9,
    title: "Food & Eating Out",
    words: [
      { german: "das Lebensmittel", article: "das", english: "food, grocery item", genderTip: "compound: last component Mittel → das", pos: "noun" },
      { german: "das Gericht", article: "das", english: "dish (prepared food), meal", genderTip: "no rule — memorise: das Gericht", pos: "noun" },
      { german: "die Küche", article: "die", english: "kitchen; also cuisine", genderTip: "no rule — memorise: die Küche", pos: "noun" },
      { german: "kochen", article: null, english: "to cook; to boil", genderTip: null, pos: "verb" },
      { german: "backen", article: null, english: "to bake", genderTip: null, pos: "verb" },
      { german: "das Rezept", article: "das", english: "recipe", genderTip: "no rule — memorise: das Rezept", pos: "noun" },
      { german: "die Zutat", article: "die", english: "ingredient", genderTip: "compound: last component Tat → die", pos: "noun" },
      { german: "würzen", article: null, english: "to season (with spices)", genderTip: null, pos: "verb" },
      { german: "die Gewürze", article: "die", english: "spices, seasonings", genderTip: "plural of das Gewürz → die (pl.)", pos: "noun" },
      { german: "schmecken", article: null, english: "to taste, have a flavour", genderTip: null, pos: "verb" },
      { german: "lecker", article: null, english: "delicious, tasty", genderTip: null, pos: "adj" },
      { german: "köstlich", article: null, english: "delicious, exquisite", genderTip: null, pos: "adj" },
      { german: "würzig", article: null, english: "flavorful, well-seasoned", genderTip: null, pos: "adj" },
      { german: "scharf", article: null, english: "spicy-hot; sharp", genderTip: null, pos: "adj" },
      { german: "süß", article: null, english: "sweet", genderTip: null, pos: "adj" },
      { german: "sauer", article: null, english: "sour; also angry (slang)", genderTip: null, pos: "adj" },
      { german: "bitter", article: null, english: "bitter", genderTip: null, pos: "adj" },
      { german: "salzig", article: null, english: "salty", genderTip: null, pos: "adj" },
      { german: "frisch", article: null, english: "fresh", genderTip: null, pos: "adj" },
      { german: "die Mahlzeit", article: "die", english: "meal (time of eating)", genderTip: "compound: last component Zeit → die", pos: "noun" },
      { german: "die Vorspeise", article: "die", english: "appetiser, starter", genderTip: "compound: last component Speise → die", pos: "noun" },
      { german: "die Hauptspeise", article: "die", english: "main course", genderTip: "compound: last component Speise → die", pos: "noun" },
      { german: "der Nachtisch", article: "der", english: "dessert", genderTip: "compound: last component Tisch → der", pos: "noun" },
      { german: "das Getränk", article: "das", english: "drink, beverage", genderTip: "no rule — memorise: das Getränk", pos: "noun" },
      { german: "der Geschmack", article: "der", english: "taste, flavour; also style", genderTip: "no rule — memorise: der Geschmack", pos: "noun" },
      { german: "die Spezialität", article: "die", english: "speciality (culinary)", genderTip: "-tät words are always feminine → die", pos: "noun" },
      { german: "das Restaurant", article: "das", english: "restaurant", genderTip: "no rule — memorise: das Restaurant", pos: "noun" },
      { german: "das Café", article: "das", english: "café", genderTip: "no rule — memorise: das Café", pos: "noun" },
      { german: "die Kneipe", article: "die", english: "pub, bar (casual)", genderTip: "no rule — memorise: die Kneipe", pos: "noun" },
      { german: "die Speisekarte", article: "die", english: "menu", genderTip: "compound: last component Karte → die", pos: "noun" },
      { german: "die Rechnung", article: "die", english: "bill, check", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "das Trinkgeld", article: "das", english: "tip, gratuity", genderTip: "compound: last component Geld → das", pos: "noun" },
      { german: "die Reservierung", article: "die", english: "reservation", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "reservieren", article: null, english: "to reserve", genderTip: null, pos: "verb" },
      { german: "der Kellner", article: "der", english: "waiter, server (male)", genderTip: "-er agent noun (male person) → der", pos: "noun" },
      { german: "die Bedienung", article: "die", english: "service; also way to address a waiter", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Allergie", article: "die", english: "allergy", genderTip: "-ie words are often feminine → die", pos: "noun" },
      { german: "allergisch gegen", article: null, english: "allergic to", genderTip: null, pos: "phrase" },
    ]
  },
  {
    lesson: 10,
    title: "Useful Connecting Words",
    words: [
      { german: "weil", article: null, english: "because (subordinating — verb goes to end)", genderTip: null, pos: "conj" },
      { german: "da", article: null, english: "since, because (subordinating, often sentence-start)", genderTip: null, pos: "conj" },
      { german: "dass", article: null, english: "that (introduces subordinate clause)", genderTip: null, pos: "conj" },
      { german: "wenn", article: null, english: "if; when (for conditions/repeated events)", genderTip: null, pos: "conj" },
      { german: "falls", article: null, english: "in case, if (conditional)", genderTip: null, pos: "conj" },
      { german: "obwohl", article: null, english: "although (expresses contrast)", genderTip: null, pos: "conj" },
      { german: "während", article: null, english: "while, whereas", genderTip: null, pos: "conj" },
      { german: "damit", article: null, english: "so that, in order that (different subject)", genderTip: null, pos: "conj" },
      { german: "sondern", article: null, english: "but rather (used after a negation: nicht A, sondern B)", genderTip: null, pos: "conj" },
      { german: "denn", article: null, english: "because, for (coordinating — no word order change)", genderTip: null, pos: "conj" },
      { german: "deshalb", article: null, english: "therefore, that's why", genderTip: null, pos: "adv" },
      { german: "deswegen", article: null, english: "therefore, for that reason (synonym of deshalb)", genderTip: null, pos: "adv" },
      { german: "daher", article: null, english: "hence, therefore", genderTip: null, pos: "adv" },
      { german: "trotzdem", article: null, english: "nevertheless, in spite of that", genderTip: null, pos: "adv" },
      { german: "dennoch", article: null, english: "nevertheless, nonetheless (formal/written)", genderTip: null, pos: "adv" },
      { german: "stattdessen", article: null, english: "instead (of that)", genderTip: null, pos: "adv" },
      { german: "außerdem", article: null, english: "besides, moreover", genderTip: null, pos: "adv" },
      { german: "jedoch", article: null, english: "however, though (formal 'but')", genderTip: null, pos: "adv" },
      { german: "allerdings", article: null, english: "however, indeed; actually yes but…", genderTip: null, pos: "adv" },
      { german: "zum Beispiel", article: null, english: "for example (abbreviated z.B.)", genderTip: null, pos: "phrase" },
      { german: "beispielsweise", article: null, english: "for example (synonym of zum Beispiel)", genderTip: null, pos: "adv" },
      { german: "im Gegenteil", article: null, english: "on the contrary", genderTip: null, pos: "phrase" },
      { german: "einerseits … andererseits", article: null, english: "on the one hand … on the other hand", genderTip: null, pos: "phrase" },
      { german: "nicht nur … sondern auch", article: null, english: "not only … but also", genderTip: null, pos: "phrase" },
      { german: "entweder … oder", article: null, english: "either … or", genderTip: null, pos: "phrase" },
      { german: "weder … noch", article: null, english: "neither … nor", genderTip: null, pos: "phrase" },
      { german: "schließlich", article: null, english: "after all; finally, in the end", genderTip: null, pos: "adv" },
      { german: "letztendlich", article: null, english: "ultimately, in the end", genderTip: null, pos: "adv" },
      { german: "kurz gesagt", article: null, english: "in short, to put it briefly", genderTip: null, pos: "phrase" },
      { german: "im Allgemeinen", article: null, english: "in general, generally", genderTip: null, pos: "phrase" },
      { german: "übrigens", article: null, english: "by the way", genderTip: null, pos: "adv" },
      { german: "hoffentlich", article: null, english: "hopefully", genderTip: null, pos: "adv" },
      { german: "zum Glück", article: null, english: "fortunately, luckily", genderTip: null, pos: "phrase" },
      { german: "leider", article: null, english: "unfortunately", genderTip: null, pos: "adv" },
      { german: "eigentlich", article: null, english: "actually, really (in truth)", genderTip: null, pos: "adv" },
      { german: "um … zu", article: null, english: "in order to (same subject: Um fit zu bleiben, …)", genderTip: null, pos: "phrase" },
    ]
  },
  {
    lesson: 11,
    title: "Sequencing & Storytelling",
    words: [
      { german: "zuerst", article: null, english: "first of all", genderTip: null, pos: "adv" },
      { german: "erstens", article: null, english: "firstly (when listing: erstens, zweitens…)", genderTip: null, pos: "adv" },
      { german: "dann", article: null, english: "then", genderTip: null, pos: "adv" },
      { german: "danach", article: null, english: "after that", genderTip: null, pos: "adv" },
      { german: "als Nächstes", article: null, english: "next, as the next thing", genderTip: null, pos: "phrase" },
      { german: "später", article: null, english: "later, later on", genderTip: null, pos: "adv" },
      { german: "nachher", article: null, english: "afterwards, later", genderTip: null, pos: "adv" },
      { german: "anschließend", article: null, english: "subsequently, afterwards", genderTip: null, pos: "adv" },
      { german: "zum Schluss", article: null, english: "finally, in conclusion", genderTip: null, pos: "phrase" },
      { german: "plötzlich", article: null, english: "suddenly", genderTip: null, pos: "adv" },
      { german: "auf einmal", article: null, english: "all of a sudden, suddenly", genderTip: null, pos: "phrase" },
      { german: "mittlerweile", article: null, english: "meanwhile, by now (time has passed)", genderTip: null, pos: "adv" },
      { german: "währenddessen", article: null, english: "meanwhile, during that time", genderTip: null, pos: "adv" },
      { german: "in der Zwischenzeit", article: null, english: "in the meantime", genderTip: null, pos: "phrase" },
      { german: "damals", article: null, english: "back then, at that time (past)", genderTip: null, pos: "adv" },
      { german: "früher", article: null, english: "earlier; in the past (former times/habits)", genderTip: null, pos: "adv" },
      { german: "bis dahin", article: null, english: "until then", genderTip: null, pos: "phrase" },
      { german: "vorher", article: null, english: "beforehand, earlier", genderTip: null, pos: "adv" },
      { german: "bevor", article: null, english: "before (conjunction)", genderTip: null, pos: "conj" },
      { german: "nachdem", article: null, english: "after (conjunction, needs past perfect for sequence)", genderTip: null, pos: "conj" },
      { german: "erzählen", article: null, english: "to tell, narrate a story", genderTip: null, pos: "verb" },
      { german: "berichten", article: null, english: "to report, tell about", genderTip: null, pos: "verb" },
      { german: "die Geschichte", article: "die", english: "story; also history", genderTip: "no rule — memorise: die Geschichte", pos: "noun" },
      { german: "die Erzählung", article: "die", english: "narration, tale", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "passieren", article: null, english: "to happen (Was ist passiert?)", genderTip: null, pos: "verb" },
      { german: "geschehen", article: null, english: "to occur, happen (formal)", genderTip: null, pos: "verb" },
      { german: "stattfinden", article: null, english: "to take place (an event)", genderTip: null, pos: "verb" },
      { german: "erleben", article: null, english: "to experience, live through an event", genderTip: null, pos: "verb" },
      { german: "das Erlebnis", article: "das", english: "experience (memorable event lived through)", genderTip: "-nis → usually das", pos: "noun" },
      { german: "spannend", article: null, english: "exciting, suspenseful", genderTip: null, pos: "adj" },
      { german: "die Spannung", article: "die", english: "tension, suspense", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "langweilig", article: null, english: "boring", genderTip: null, pos: "adj" },
      { german: "zusammenfassen", article: null, english: "to summarise", genderTip: null, pos: "verb" },
      { german: "die Zusammenfassung", article: "die", english: "summary", genderTip: "-ung words are always feminine → die", pos: "noun" },
    ]
  },
  {
    lesson: 12,
    title: "Media & Technology",
    words: [
      { german: "das Handy", article: "das", english: "mobile phone", genderTip: "no rule — memorise: das Handy", pos: "noun" },
      { german: "das Smartphone", article: "das", english: "smartphone", genderTip: "-phone compound → das", pos: "noun" },
      { german: "anrufen", article: null, english: "to call (on the phone)", genderTip: null, pos: "verb" },
      { german: "der Anruf", article: "der", english: "phone call", genderTip: "compound: last component Ruf → der", pos: "noun" },
      { german: "die Nachricht", article: "die", english: "message, news", genderTip: "no rule — memorise: die Nachricht", pos: "noun" },
      { german: "schicken", article: null, english: "to send", genderTip: null, pos: "verb" },
      { german: "empfangen", article: null, english: "to receive", genderTip: null, pos: "verb" },
      { german: "die E-Mail", article: "die", english: "email", genderTip: "no rule — memorise: die E-Mail", pos: "noun" },
      { german: "das Tablet", article: "das", english: "tablet (device)", genderTip: "no rule — memorise: das Tablet", pos: "noun" },
      { german: "der Laptop", article: "der", english: "laptop", genderTip: "no rule — memorise: der Laptop", pos: "noun" },
      { german: "der Computer", article: "der", english: "computer", genderTip: "-er agent/device noun → der", pos: "noun" },
      { german: "der Bildschirm", article: "der", english: "screen", genderTip: "compound: last component Schirm → der", pos: "noun" },
      { german: "die Tastatur", article: "die", english: "keyboard", genderTip: "-ur suffix → usually die", pos: "noun" },
      { german: "das Ladegerät", article: "das", english: "charger", genderTip: "compound: last component Gerät → das", pos: "noun" },
      { german: "die App", article: "die", english: "app", genderTip: "no rule — memorise: die App", pos: "noun" },
      { german: "herunterladen", article: null, english: "to download", genderTip: null, pos: "verb" },
      { german: "hochladen", article: null, english: "to upload", genderTip: null, pos: "verb" },
      { german: "speichern", article: null, english: "to save (a file)", genderTip: null, pos: "verb" },
      { german: "löschen", article: null, english: "to delete", genderTip: null, pos: "verb" },
      { german: "die Datei", article: "die", english: "file (computer)", genderTip: "no rule — memorise: die Datei", pos: "noun" },
      { german: "die Festplatte", article: "die", english: "hard drive", genderTip: "compound: last component Platte → die", pos: "noun" },
      { german: "das Internet", article: "das", english: "the internet", genderTip: "no rule — memorise: das Internet", pos: "noun" },
      { german: "surfen", article: null, english: "to surf (the web)", genderTip: null, pos: "verb" },
      { german: "die Website", article: "die", english: "website", genderTip: "no rule — memorise: die Website", pos: "noun" },
      { german: "das Passwort", article: "das", english: "password", genderTip: "compound: last component Wort → das", pos: "noun" },
      { german: "sich einloggen", article: null, english: "to log in", genderTip: null, pos: "verb" },
      { german: "die sozialen Medien", article: "die", english: "social media", genderTip: "plural: Medien → die (pl.)", pos: "noun" },
      { german: "das soziale Netzwerk", article: "das", english: "social network", genderTip: "compound: last component Werk → das", pos: "noun" },
      { german: "posten", article: null, english: "to post (on social media)", genderTip: null, pos: "verb" },
      { german: "teilen", article: null, english: "to share", genderTip: null, pos: "verb" },
      { german: "liken", article: null, english: "to like (on social media)", genderTip: null, pos: "verb" },
      { german: "kommentieren", article: null, english: "to comment", genderTip: null, pos: "verb" },
      { german: "folgen", article: null, english: "to follow", genderTip: null, pos: "verb" },
      { german: "die Werbung", article: "die", english: "advertisement", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Zeitung", article: "die", english: "newspaper", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Zeitschrift", article: "die", english: "magazine", genderTip: "compound: last component Schrift → die", pos: "noun" },
      { german: "die Nachrichtensendung", article: "die", english: "news broadcast", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Sender", article: "der", english: "TV/radio channel", genderTip: "-er agent noun → der", pos: "noun" },
      { german: "fernsehen", article: null, english: "to watch TV", genderTip: null, pos: "verb" },
      { german: "der Fernseher", article: "der", english: "TV set", genderTip: "-er device noun → der", pos: "noun" },
      { german: "die Fernbedienung", article: "die", english: "remote control", genderTip: "-ung words are always feminine → die", pos: "noun" },
    ]
  },
  {
    lesson: 13,
    title: "Travel & Tourism",
    words: [
      { german: "reisen", article: null, english: "to travel", genderTip: null, pos: "verb" },
      { german: "die Reise", article: "die", english: "trip, journey", genderTip: "no rule — memorise: die Reise", pos: "noun" },
      { german: "der Urlaub", article: "der", english: "holiday, vacation", genderTip: "no rule — memorise: der Urlaub", pos: "noun" },
      { german: "das Reiseziel", article: "das", english: "travel destination", genderTip: "compound: last component Ziel → das", pos: "noun" },
      { german: "buchen", article: null, english: "to book", genderTip: null, pos: "verb" },
      { german: "die Buchung", article: "die", english: "booking", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "das Hotel", article: "das", english: "hotel", genderTip: "no rule — memorise: das Hotel", pos: "noun" },
      { german: "die Unterkunft", article: "die", english: "accommodation", genderTip: "compound: last component Kunft → die (memorise)", pos: "noun" },
      { german: "übernachten", article: null, english: "to stay overnight", genderTip: null, pos: "verb" },
      { german: "die Übernachtung", article: "die", english: "overnight stay", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Flug", article: "der", english: "flight", genderTip: "no rule — memorise: der Flug", pos: "noun" },
      { german: "fliegen", article: null, english: "to fly", genderTip: null, pos: "verb" },
      { german: "der Flughafen", article: "der", english: "airport", genderTip: "compound: last component Hafen → der", pos: "noun" },
      { german: "der Zug", article: "der", english: "train", genderTip: "no rule — memorise: der Zug", pos: "noun" },
      { german: "der Fahrplan", article: "der", english: "timetable, schedule", genderTip: "compound: last component Plan → der", pos: "noun" },
      { german: "die Verspätung", article: "die", english: "delay", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Abfahrt", article: "die", english: "departure (train)", genderTip: "compound: last component Fahrt → die", pos: "noun" },
      { german: "die Ankunft", article: "die", english: "arrival", genderTip: "compound: last component Kunft → die (memorise)", pos: "noun" },
      { german: "die Reiseversicherung", article: "die", english: "travel insurance", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Reisepass", article: "der", english: "passport", genderTip: "compound: last component Pass → der", pos: "noun" },
      { german: "das Visum", article: "das", english: "visa", genderTip: "-um words → usually das", pos: "noun" },
      { german: "der Zoll", article: "der", english: "customs", genderTip: "no rule — memorise: der Zoll", pos: "noun" },
      { german: "der Koffer", article: "der", english: "suitcase", genderTip: "no rule — memorise: der Koffer", pos: "noun" },
      { german: "das Gepäck", article: "das", english: "luggage", genderTip: "no rule — memorise: das Gepäck", pos: "noun" },
      { german: "einpacken", article: null, english: "to pack (a suitcase)", genderTip: null, pos: "verb" },
      { german: "auspacken", article: null, english: "to unpack", genderTip: null, pos: "verb" },
      { german: "der Stadtplan", article: "der", english: "city map", genderTip: "compound: last component Plan → der", pos: "noun" },
      { german: "die Sehenswürdigkeit", article: "die", english: "tourist attraction, sight", genderTip: "-keit words are always feminine → die", pos: "noun" },
      { german: "besichtigen", article: null, english: "to visit (a sight)", genderTip: null, pos: "verb" },
      { german: "der Tourist", article: "der", english: "tourist (male)", genderTip: "-ist person noun (male) → der", pos: "noun" },
      { german: "das Souvenir", article: "das", english: "souvenir", genderTip: "no rule — memorise: das Souvenir", pos: "noun" },
      { german: "der Ausflug", article: "der", english: "excursion, day trip", genderTip: "compound: last component Flug → der", pos: "noun" },
      { german: "das Abenteuer", article: "das", english: "adventure", genderTip: "no rule — memorise: das Abenteuer", pos: "noun" },
      { german: "wandern", article: null, english: "to hike", genderTip: null, pos: "verb" },
      { german: "die Wanderung", article: "die", english: "hike", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Küste", article: "die", english: "coast", genderTip: "no rule — memorise: die Küste", pos: "noun" },
      { german: "das Meer", article: "das", english: "sea, ocean", genderTip: "no rule — memorise: das Meer", pos: "noun" },
      { german: "das Gebirge", article: "das", english: "mountain range", genderTip: "collective noun with Ge- prefix → das", pos: "noun" },
      { german: "das Zelt", article: "das", english: "tent", genderTip: "no rule — memorise: das Zelt", pos: "noun" },
      { german: "zelten", article: null, english: "to camp", genderTip: null, pos: "verb" },
      { german: "die Jugendherberge", article: "die", english: "youth hostel", genderTip: "compound: last component Herberge → die", pos: "noun" },
    ]
  },
  {
    lesson: 14,
    title: "Emotions & Reactions",
    words: [
      { german: "die Emotion", article: "die", english: "emotion", genderTip: "-ion words are always feminine → die", pos: "noun" },
      { german: "das Gefühl", article: "das", english: "feeling", genderTip: "no rule — memorise: das Gefühl", pos: "noun" },
      { german: "sich fühlen", article: null, english: "to feel (reflexive)", genderTip: null, pos: "verb" },
      { german: "glücklich", article: null, english: "happy", genderTip: null, pos: "adj" },
      { german: "die Freude", article: "die", english: "joy", genderTip: "no rule — memorise: die Freude", pos: "noun" },
      { german: "sich freuen über", article: null, english: "to be happy about something", genderTip: null, pos: "verb" },
      { german: "sich freuen auf", article: null, english: "to look forward to something", genderTip: null, pos: "verb" },
      { german: "zufrieden", article: null, english: "satisfied", genderTip: null, pos: "adj" },
      { german: "stolz", article: null, english: "proud", genderTip: null, pos: "adj" },
      { german: "erleichtert", article: null, english: "relieved", genderTip: null, pos: "adj" },
      { german: "überrascht", article: null, english: "surprised", genderTip: null, pos: "adj" },
      { german: "dankbar", article: null, english: "thankful, grateful", genderTip: null, pos: "adj" },
      { german: "nervös", article: null, english: "nervous", genderTip: null, pos: "adj" },
      { german: "aufgeregt", article: null, english: "excited; agitated", genderTip: null, pos: "adj" },
      { german: "wütend", article: null, english: "angry", genderTip: null, pos: "adj" },
      { german: "enttäuscht", article: null, english: "disappointed", genderTip: null, pos: "adj" },
      { german: "traurig", article: null, english: "sad", genderTip: null, pos: "adj" },
      { german: "weinen", article: null, english: "to cry", genderTip: null, pos: "verb" },
      { german: "lachen", article: null, english: "to laugh", genderTip: null, pos: "verb" },
      { german: "sich schämen", article: null, english: "to be ashamed", genderTip: null, pos: "verb" },
      { german: "sich ärgern über", article: null, english: "to get annoyed about", genderTip: null, pos: "verb" },
      { german: "der Ärger", article: "der", english: "annoyance, irritation", genderTip: "no rule — memorise: der Ärger", pos: "noun" },
      { german: "die Wut", article: "die", english: "rage, fury", genderTip: "no rule — memorise: die Wut", pos: "noun" },
      { german: "die Angst", article: "die", english: "fear, anxiety", genderTip: "no rule — memorise: die Angst", pos: "noun" },
      { german: "ängstlich", article: null, english: "anxious, fearful", genderTip: null, pos: "adj" },
      { german: "sich fürchten vor", article: null, english: "to be afraid of", genderTip: null, pos: "verb" },
      { german: "beruhigen", article: null, english: "to calm down (someone)", genderTip: null, pos: "verb" },
      { german: "sich beruhigen", article: null, english: "to calm oneself down", genderTip: null, pos: "verb" },
      { german: "trösten", article: null, english: "to comfort", genderTip: null, pos: "verb" },
      { german: "bewältigen", article: null, english: "to cope with", genderTip: null, pos: "verb" },
      { german: "aushalten", article: null, english: "to endure, bear", genderTip: null, pos: "verb" },
      { german: "empfinden", article: null, english: "to feel, sense", genderTip: null, pos: "verb" },
      { german: "mitfühlen", article: null, english: "to empathize", genderTip: null, pos: "verb" },
      { german: "das Mitgefühl", article: "das", english: "compassion, empathy", genderTip: "compound: last component Gefühl → das", pos: "noun" },
      { german: "eifersüchtig", article: null, english: "jealous", genderTip: null, pos: "adj" },
      { german: "neidisch", article: null, english: "envious", genderTip: null, pos: "adj" },
      { german: "die Stimmung", article: "die", english: "mood, atmosphere", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "empfindlich", article: null, english: "sensitive", genderTip: null, pos: "adj" },
      { german: "begeistert", article: null, english: "enthusiastic", genderTip: null, pos: "adj" },
      { german: "die Begeisterung", article: "die", english: "enthusiasm", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "gleichgültig", article: null, english: "indifferent", genderTip: null, pos: "adj" },
    ]
  },
  {
    lesson: 15,
    title: "Politics & Society",
    words: [
      { german: "die Politik", article: "die", english: "politics", genderTip: "-ik words are often feminine → die", pos: "noun" },
      { german: "politisch", article: null, english: "political", genderTip: null, pos: "adj" },
      { german: "der Politiker", article: "der", english: "politician (male)", genderTip: "-er person noun (male) → der", pos: "noun" },
      { german: "die Regierung", article: "die", english: "government", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "das Parlament", article: "das", english: "parliament", genderTip: "-ment words → usually das", pos: "noun" },
      { german: "der Bundestag", article: "der", english: "German federal parliament", genderTip: "compound: last component Tag → der", pos: "noun" },
      { german: "die Wahl", article: "die", english: "election, vote", genderTip: "no rule — memorise: die Wahl", pos: "noun" },
      { german: "wählen", article: null, english: "to vote; to choose", genderTip: null, pos: "verb" },
      { german: "die Stimme", article: "die", english: "vote; also voice", genderTip: "no rule — memorise: die Stimme", pos: "noun" },
      { german: "die Demokratie", article: "die", english: "democracy", genderTip: "-ie words are often feminine → die", pos: "noun" },
      { german: "demokratisch", article: null, english: "democratic", genderTip: null, pos: "adj" },
      { german: "das Gesetz", article: "das", english: "law", genderTip: "no rule — memorise: das Gesetz", pos: "noun" },
      { german: "legal", article: null, english: "legal", genderTip: null, pos: "adj" },
      { german: "illegal", article: null, english: "illegal", genderTip: null, pos: "adj" },
      { german: "der Richter", article: "der", english: "judge (male)", genderTip: "-er person noun (male) → der", pos: "noun" },
      { german: "das Urteil", article: "das", english: "verdict, judgement", genderTip: "no rule — memorise: das Urteil", pos: "noun" },
      { german: "das Verbrechen", article: "das", english: "crime", genderTip: "nominalised verb (Ge- + brechen) → das", pos: "noun" },
      { german: "der Täter", article: "der", english: "perpetrator (male)", genderTip: "-er agent noun → der", pos: "noun" },
      { german: "der Zeuge", article: "der", english: "witness (male)", genderTip: "person noun → der", pos: "noun" },
      { german: "der Bürger", article: "der", english: "citizen (male)", genderTip: "-er person noun (male) → der", pos: "noun" },
      { german: "die Gesellschaft", article: "die", english: "society", genderTip: "-schaft words are always feminine → die", pos: "noun" },
      { german: "sozial", article: null, english: "social", genderTip: null, pos: "adj" },
      { german: "das Sozialsystem", article: "das", english: "social system", genderTip: "compound: last component System → das", pos: "noun" },
      { german: "die Ungleichheit", article: "die", english: "inequality", genderTip: "-heit words are always feminine → die", pos: "noun" },
      { german: "gerecht", article: null, english: "fair, just", genderTip: null, pos: "adj" },
      { german: "ungerecht", article: null, english: "unfair, unjust", genderTip: null, pos: "adj" },
      { german: "die Gerechtigkeit", article: "die", english: "justice, fairness", genderTip: "-keit words are always feminine → die", pos: "noun" },
      { german: "das Menschenrecht", article: "das", english: "human right", genderTip: "compound: last component Recht → das", pos: "noun" },
      { german: "die Meinungsfreiheit", article: "die", english: "freedom of opinion", genderTip: "-heit words are always feminine → die", pos: "noun" },
      { german: "die Pressefreiheit", article: "die", english: "freedom of the press", genderTip: "-heit words are always feminine → die", pos: "noun" },
      { german: "aktuell", article: null, english: "current, up-to-date", genderTip: null, pos: "adj" },
      { german: "berichten", article: null, english: "to report", genderTip: null, pos: "verb" },
      { german: "der Bericht", article: "der", english: "report", genderTip: "no rule — memorise: der Bericht", pos: "noun" },
      { german: "demonstrieren", article: null, english: "to protest, demonstrate", genderTip: null, pos: "verb" },
      { german: "die Demonstration", article: "die", english: "protest, demonstration", genderTip: "-tion words are always feminine → die", pos: "noun" },
      { german: "die Umweltpolitik", article: "die", english: "environmental policy", genderTip: "-ik words → often die; compound last: Politik → die", pos: "noun" },
      { german: "die Außenpolitik", article: "die", english: "foreign policy", genderTip: "-ik words are often feminine → die", pos: "noun" },
      { german: "die Innenpolitik", article: "die", english: "domestic policy", genderTip: "-ik words are often feminine → die", pos: "noun" },
      { german: "die Wirtschaft", article: "die", english: "economy", genderTip: "-schaft words are always feminine → die", pos: "noun" },
      { german: "wirtschaftlich", article: null, english: "economic(ally)", genderTip: null, pos: "adj" },
      { german: "die Steuer", article: "die", english: "tax", genderTip: "no rule — memorise: die Steuer", pos: "noun" },
      { german: "der Staat", article: "der", english: "state, country", genderTip: "no rule — memorise: der Staat", pos: "noun" },
      { german: "die EU (Europäische Union)", article: "die", english: "European Union (EU)", genderTip: "compound: last component Union → die", pos: "noun" },
    ]
  },
  {
    lesson: 16,
    title: "Home & Household",
    words: [
      { german: "der Alltag", article: "der", english: "everyday life", genderTip: "compound: last component Tag → der", pos: "noun" },
      { german: "der Staub", article: "der", english: "dust", genderTip: "no rule — memorise: der Staub", pos: "noun" },
      { german: "staubsaugen", article: null, english: "to vacuum", genderTip: null, pos: "verb" },
      { german: "der Staubsauger", article: "der", english: "vacuum cleaner", genderTip: "-er device noun → der", pos: "noun" },
      { german: "die Wäsche", article: "die", english: "laundry, washing", genderTip: "no rule — memorise: die Wäsche", pos: "noun" },
      { german: "die Waschmaschine", article: "die", english: "washing machine", genderTip: "compound: last component Maschine → die", pos: "noun" },
      { german: "bügeln", article: null, english: "to iron", genderTip: null, pos: "verb" },
      { german: "das Bügeleisen", article: "das", english: "iron (appliance)", genderTip: "compound: last component Eisen → das", pos: "noun" },
      { german: "das Geschirr", article: "das", english: "dishes, crockery", genderTip: "no rule — memorise: das Geschirr", pos: "noun" },
      { german: "abwaschen", article: null, english: "to wash up (dishes)", genderTip: null, pos: "verb" },
      { german: "der Geschirrspüler", article: "der", english: "dishwasher", genderTip: "-er device noun → der", pos: "noun" },
      { german: "den Müll rausbringen", article: null, english: "to take out the rubbish", genderTip: null, pos: "phrase" },
      { german: "der Mülleimer", article: "der", english: "rubbish bin", genderTip: "compound: last component Eimer → der", pos: "noun" },
      { german: "die Hausarbeit", article: "die", english: "housework", genderTip: "compound: last component Arbeit → die", pos: "noun" },
      { german: "der Haushalt", article: "der", english: "household", genderTip: "compound: last component Halt → der", pos: "noun" },
      { german: "die Verantwortung", article: "die", english: "responsibility", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "erledigen", article: null, english: "to take care of, complete a task", genderTip: null, pos: "verb" },
      { german: "der Mitbewohner", article: "der", english: "housemate (male)", genderTip: "-er person noun (male) → der", pos: "noun" },
      { german: "die WG (Wohngemeinschaft)", article: "die", english: "shared flat", genderTip: "-schaft words are always feminine → die", pos: "noun" },
      { german: "die Ordnung", article: "die", english: "order, tidiness", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "ordentlich", article: null, english: "tidy, neat", genderTip: null, pos: "adj" },
      { german: "chaotisch", article: null, english: "messy, chaotic", genderTip: null, pos: "adj" },
    ]
  },
  {
    lesson: 17,
    title: "Work & Office Life",
    words: [
      { german: "der Arbeitsplatz", article: "der", english: "workplace", genderTip: "compound: last component Platz → der", pos: "noun" },
      { german: "der Angestellte", article: "der", english: "employee (male)", genderTip: "adjectival noun → der (male)", pos: "noun" },
      { german: "die Firma", article: "die", english: "company, firm", genderTip: "no rule — memorise: die Firma", pos: "noun" },
      { german: "das Unternehmen", article: "das", english: "business, corporation", genderTip: "nominalised verb → das", pos: "noun" },
      { german: "die Abteilung", article: "die", english: "department", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Besprechung", article: "die", english: "meeting", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Sitzung", article: "die", english: "formal meeting, session", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Termin", article: "der", english: "appointment, deadline", genderTip: "no rule — memorise: der Termin", pos: "noun" },
      { german: "das Projekt", article: "das", english: "project", genderTip: "no rule — memorise: das Projekt", pos: "noun" },
      { german: "das Team", article: "das", english: "team", genderTip: "no rule — memorise: das Team", pos: "noun" },
      { german: "die Aufgabe", article: "die", english: "task, assignment", genderTip: "compound: last component Gabe → die", pos: "noun" },
      { german: "pünktlich", article: null, english: "punctual, on time", genderTip: null, pos: "adj" },
      { german: "das Gehalt", article: "das", english: "salary", genderTip: "no rule — memorise: das Gehalt", pos: "noun" },
      { german: "die Bezahlung", article: "die", english: "payment", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Bewerbung", article: "die", english: "job application", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "sich bewerben", article: null, english: "to apply (for a job)", genderTip: null, pos: "verb" },
      { german: "der Lebenslauf", article: "der", english: "CV, résumé", genderTip: "compound: last component Lauf → der", pos: "noun" },
      { german: "das Vorstellungsgespräch", article: "das", english: "job interview", genderTip: "compound: last component Gespräch → das", pos: "noun" },
      { german: "kündigen", article: null, english: "to resign; to fire (depending on subject)", genderTip: null, pos: "verb" },
      { german: "die Kündigung", article: "die", english: "resignation, termination", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "das Arbeitslosengeld", article: "das", english: "unemployment benefit", genderTip: "compound: last component Geld → das", pos: "noun" },
      { german: "die Vollzeit", article: "die", english: "full-time", genderTip: "compound: last component Zeit → die", pos: "noun" },
      { german: "die Teilzeit", article: "die", english: "part-time", genderTip: "compound: last component Zeit → die", pos: "noun" },
      { german: "das Homeoffice", article: "das", english: "remote work, working from home", genderTip: "English loanword → das", pos: "noun" },
      { german: "aufsteigen", article: null, english: "to get promoted, rise", genderTip: null, pos: "verb" },
      { german: "die Beförderung", article: "die", english: "promotion (at work)", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "verantwortlich", article: null, english: "responsible", genderTip: null, pos: "adj" },
      { german: "unter Druck stehen", article: null, english: "to be under pressure", genderTip: null, pos: "phrase" },
      { german: "die Zufriedenheit", article: "die", english: "satisfaction, contentment", genderTip: "-heit words are always feminine → die", pos: "noun" },
    ]
  },
  {
    lesson: 18,
    title: "Communication & Interaction",
    words: [
      { german: "mitteilen", article: null, english: "to inform, communicate", genderTip: null, pos: "verb" },
      { german: "reden", article: null, english: "to talk, speak", genderTip: null, pos: "verb" },
      { german: "sich unterhalten mit", article: null, english: "to have a conversation with", genderTip: null, pos: "verb" },
      { german: "die Unterhaltung", article: "die", english: "conversation; also entertainment", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "sich ausdrücken", article: null, english: "to express oneself", genderTip: null, pos: "verb" },
      { german: "der Ausdruck", article: "der", english: "expression, term", genderTip: "compound: last component Druck → der", pos: "noun" },
      { german: "die Meinung", article: "die", english: "opinion", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Standpunkt", article: "der", english: "standpoint, perspective", genderTip: "compound: last component Punkt → der", pos: "noun" },
      { german: "zustimmen", article: null, english: "to agree", genderTip: null, pos: "verb" },
      { german: "ablehnen", article: null, english: "to reject, decline", genderTip: null, pos: "verb" },
      { german: "widersprechen", article: null, english: "to contradict, disagree", genderTip: null, pos: "verb" },
      { german: "zuständig sein für", article: null, english: "to be responsible for", genderTip: null, pos: "phrase" },
      { german: "sich melden", article: null, english: "to get in touch; raise one's hand", genderTip: null, pos: "verb" },
      { german: "sich verabreden mit", article: null, english: "to make plans with someone", genderTip: null, pos: "verb" },
      { german: "die Verabredung", article: "die", english: "arrangement, appointment", genderTip: "-ung words are always feminine → die", pos: "noun" },
    ]
  },
  {
    lesson: 19,
    title: "Celebrations & Traditions",
    words: [
      { german: "der Brauch", article: "der", english: "custom, ritual, tradition", genderTip: "no rule — memorise: der Brauch", pos: "noun" },
      { german: "das Ereignis", article: "das", english: "event, occasion", genderTip: "-nis → usually das", pos: "noun" },
      { german: "der Feiertag", article: "der", english: "public holiday", genderTip: "compound: last component Tag → der", pos: "noun" },
      { german: "die Adventszeit", article: "die", english: "Advent season", genderTip: "compound: last component Zeit → die", pos: "noun" },
      { german: "der Adventskranz", article: "der", english: "Advent wreath", genderTip: "compound: last component Kranz → der", pos: "noun" },
      { german: "das Weihnachtslied", article: "das", english: "Christmas carol", genderTip: "compound: last component Lied → das", pos: "noun" },
      { german: "der Weihnachtsbaum", article: "der", english: "Christmas tree", genderTip: "compound: last component Baum → der", pos: "noun" },
      { german: "der Glückwunsch", article: "der", english: "congratulation, greeting", genderTip: "compound: last component Wunsch → der", pos: "noun" },
      { german: "anstoßen auf", article: null, english: "to toast to (e.g. at a party)", genderTip: null, pos: "verb" },
      { german: "der Gastgeber", article: "der", english: "host (male)", genderTip: "-er person noun (male) → der", pos: "noun" },
      { german: "die Dekoration", article: "die", english: "decoration", genderTip: "-tion words are always feminine → die", pos: "noun" },
      { german: "der Umzug", article: "der", english: "parade, procession; also moving house", genderTip: "compound: last component Zug → der", pos: "noun" },
      { german: "die Verkleidung", article: "die", english: "costume, disguise", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "sich verkleiden", article: null, english: "to dress up (in costume)", genderTip: null, pos: "verb" },
      { german: "die Kerze", article: "die", english: "candle", genderTip: "no rule — memorise: die Kerze", pos: "noun" },
    ]
  },
  {
    lesson: 20,
    title: "Immigration & Integration",
    words: [
      { german: "die Migration", article: "die", english: "migration", genderTip: "-tion words are always feminine → die", pos: "noun" },
      { german: "der Migrant", article: "der", english: "migrant (male)", genderTip: "-ant person noun (male) → der", pos: "noun" },
      { german: "der Flüchtling", article: "der", english: "refugee", genderTip: "-ling words → usually der", pos: "noun" },
      { german: "fliehen aus / vor", article: null, english: "to flee from", genderTip: null, pos: "verb" },
      { german: "die Flucht", article: "die", english: "escape, flight (from danger)", genderTip: "no rule — memorise: die Flucht", pos: "noun" },
      { german: "das Herkunftsland", article: "das", english: "country of origin", genderTip: "compound: last component Land → das", pos: "noun" },
      { german: "das Aufnahmeland", article: "das", english: "host country", genderTip: "compound: last component Land → das", pos: "noun" },
      { german: "auswandern", article: null, english: "to emigrate", genderTip: null, pos: "verb" },
      { german: "einwandern", article: null, english: "to immigrate", genderTip: null, pos: "verb" },
      { german: "der Einwanderer", article: "der", english: "immigrant (male)", genderTip: "-er person noun (male) → der", pos: "noun" },
      { german: "die Einwanderung", article: "die", english: "immigration", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Auswanderung", article: "die", english: "emigration", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Asylantrag", article: "der", english: "asylum application", genderTip: "compound: last component Antrag → der", pos: "noun" },
      { german: "Asyl beantragen", article: null, english: "to apply for asylum", genderTip: null, pos: "phrase" },
      { german: "der Aufenthaltstitel", article: "der", english: "residence permit", genderTip: "compound: last component Titel → der", pos: "noun" },
      { german: "der Ausweis", article: "der", english: "ID card", genderTip: "compound: last component Weis → der", pos: "noun" },
      { german: "die Staatsangehörigkeit", article: "die", english: "nationality", genderTip: "-keit words are always feminine → die", pos: "noun" },
      { german: "die doppelte Staatsbürgerschaft", article: "die", english: "dual citizenship", genderTip: "-schaft words are always feminine → die", pos: "noun" },
      { german: "die Behörde", article: "die", english: "government office, authority", genderTip: "no rule — memorise: die Behörde", pos: "noun" },
      { german: "das Einwohnermeldeamt", article: "das", english: "residents' registration office", genderTip: "compound: last component Amt → das", pos: "noun" },
      { german: "sich anmelden", article: null, english: "to register (at an address)", genderTip: null, pos: "verb" },
      { german: "die Anmeldung", article: "die", english: "registration", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Abmeldung", article: "die", english: "deregistration", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "die Aufenthaltserlaubnis", article: "die", english: "residence permit", genderTip: "compound: last component Erlaubnis → die (memorise)", pos: "noun" },
      { german: "die Arbeitserlaubnis", article: "die", english: "work permit", genderTip: "compound: last component Erlaubnis → die (memorise)", pos: "noun" },
      { german: "verlängern", article: null, english: "to extend (e.g. a visa)", genderTip: null, pos: "verb" },
      { german: "die Integration", article: "die", english: "integration", genderTip: "-tion words are always feminine → die", pos: "noun" },
      { german: "sich integrieren", article: null, english: "to integrate", genderTip: null, pos: "verb" },
      { german: "der Integrationskurs", article: "der", english: "integration course", genderTip: "compound: last component Kurs → der", pos: "noun" },
      { german: "die Sprachkenntnisse", article: "die", english: "language skills", genderTip: "plural → die", pos: "noun" },
      { german: "die Staatsbürgerschaft", article: "die", english: "citizenship", genderTip: "-schaft words are always feminine → die", pos: "noun" },
      { german: "eingebürgert werden", article: null, english: "to be naturalised", genderTip: null, pos: "phrase" },
      { german: "multikulturell", article: null, english: "multicultural", genderTip: null, pos: "adj" },
      { german: "die Herkunft", article: "die", english: "origin, background", genderTip: "compound: last component Kunft → die (memorise)", pos: "noun" },
      { german: "die Identität", article: "die", english: "identity", genderTip: "-tät words are always feminine → die", pos: "noun" },
      { german: "der Zusammenhalt", article: "der", english: "cohesion, solidarity", genderTip: "compound: last component Halt → der", pos: "noun" },
      { german: "die Toleranz", article: "die", english: "tolerance", genderTip: "-anz words are often feminine → die", pos: "noun" },
      { german: "fremd", article: null, english: "foreign, unfamiliar", genderTip: null, pos: "adj" },
      { german: "das Missverständnis", article: "das", english: "misunderstanding", genderTip: "-nis → usually das", pos: "noun" },
      { german: "die Gleichberechtigung", article: "die", english: "equality, equal rights", genderTip: "-ung words are always feminine → die", pos: "noun" },
      { german: "der Antrag", article: "der", english: "official application, form", genderTip: "compound: last component Trag → der", pos: "noun" },
    ]
  }
];

// Export for use in the app
if (typeof module !== 'undefined' && module.exports) {
  module.exports = LESSONS;
}
